### PR TITLE
Update requirements.txt

### PR DESCRIPTION
**Pull request by mikejgray**
# Description
Required to pip install on a Mac, likely elsewhere too but I don't think there's an arm64 wheel for this package yet

# Issues
N/A but I can open one if you want

### CODE REVIEW

**Comment by NeonBohdan** [comment]
As mentioned [here](https://github.com/NVIDIA/NeMo#pip) 
You need to install this project in two steps
Install `Cython` and only then `Nemo`
Including this into `requirements` won't help

But soon this project with be updated with ONNX, it will become more lightweight, faster and this problem will be eliminated

**Comment by mikejgray** [comment]
> As mentioned [here](https://github.com/NVIDIA/NeMo#pip) You need to install this project in two steps Install `Cython` and only then `Nemo` Including this into `requirements` won't help
> 
> But soon this project with be updated with ONNX, it will become more lightweight, faster and this problem will be eliminated

Thank you for the response. I'm working on setting this plugin up locally and wrapping it with ovos-stt-server, which meant having to install the plugin into the environment. It would be very helpful for use cases like that to have all of the installation information in this repository instead of chasing down each upstream requirement's documentation. With ONNX I imagine a similar situation.

**Comment by NeonDaniel** [comment]
> Thank you for the response. I'm working on setting this plugin up locally and wrapping it with ovos-stt-server, which meant having to install the plugin into the environment. It would be very helpful for use cases like that to have all of the installation information in this repository instead of chasing down each upstream requirement's documentation. With ONNX I imagine a similar situation.

Check out https://github.com/NeonGeckoCom/neon-stt-plugin-nemo/pull/13 where I'm adding Docker automation

EDIT: I completely missed the point here; we should have a note in the README that `Cython` must be installed first unless we get ONNX implemented first.

**Comment by NeonBohdan** [comment]
15.05.2023 onnx should be finished, in 5 days
So Instalation will become easy, and docker lightweight

**Comment by NeonBohdan** [comment]
With ONNX it will be easily installable on ARM64 too

**Pull request closed without merging**
